version: '3.8'

services:
  api:
    build: .
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - ./notebooks:/app/notebooks
      - ./data:/app/data
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000
