services:
  api:
    image: my-notebook-service:latest
    build: .
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - ./notebooks:/app/notebooks
      - ./data:/app/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 5s
      retries: 3
